item/urls.py
from .views import *
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
app_name = 'item'

urlpatterns = [
    path('', all_items, name='all'),
    path('<int:item_id>/', item_detail, name='detail'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # 코드 추가!

supply/urls.py
from .views import *
from django.urls import path
app_name = 'supply'

urlpatterns = [
    path('', buy, name='buy'),
    path('create/', create, name='create'),
    path('all/', order_list, name='order_list'),
    path('find/', find_order, name='find_order'),
    path('cancel/<int:order_id>/', cancel_order, name='cancel_order'),
    path('delete/<int:order_id>/', delete_order, name='delete_order'),
    path('is_money/<int:order_id>/', is_money_order, name='is_money_order'),
    path('change/<int:order_id>/', change_order, name='change_order'),
]

tuaz50th/urls.py
from django.contrib import admin
from django.urls import path, include
from supply import views
from guestbook import views
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.balloon_list, name='home'),
    
    path('item/', include('item.urls')),
    path('buy/', include('supply.urls')),
    path('about/', about, name='about'),
    path('blockgame/', blockgame, name='blockgame'),
    path('audiotest/', audiotest, name='audiotest'),
    path('intro/', intro, name='intro'),
    path('leehjhjhj/', my, name='my'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tuaz50th/views.py
from django.shortcuts import render


def about(request):
    return render(request, 'about.html')


def blockgame(request):
    return render(request, 'blockgame.html')

def audiotest(request):
    return render(request, 'audiotest.html')

def intro(request):
    return render(request, 'intro.html')

def my(request):
    return render(request, 'my.html')

tuaz50th/templates/about copy.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<body>
    <section class="homeHero">
          <div class="homeHero--inner">
              <h2 class="homeHero__title">
                  <div style="position:relative;display:inline-block;">Turk</div>
                  <div style="position:relative;display:inline-block;">Azeri</div>
                  <div style="position:relative;display:inline-block;">50th</div>
                  <div style="position:relative;display:inline-block;">Anniversary</div>
              </h2>
          </div>
      </section>
      <div class="cb-cursor">
          <div class="cb-cursor-text"></div>
          <div class="cb-cursor-video">
              <div><video id="reel-clips" class="cursor-clips" preload="" loop="" muted="" playsinline="" autoplay="">
                      <source src="https://cdn.poolhouse.co/wp-content/uploads/2021/06/02213043/clips.mp4"
                          type="video/mp4">
                  </video></div>
          </div>
      </div>
    </body>
<style>
    *{
    margin: 0;padding: 0;box-sizing: border-box; }
body {
    color: #fff;
    background: #1b1b1b;
    width: 100vw;
    font-size: 1.6rem;
    line-height: 2.2rem;
    font-family: proxima-nova,sans-serif;
    font-weight: 400;
    font-style: normal;
    overflow-x: hidden;
}
.homeHero {
    width: 100vw;
    overflow: hidden;
    padding-top: 0;
}
.homeHero--inner {
	width: 100%;
	height: 100%;
	position: relative;
	padding: 130px 0 0 0;
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
}
.homeHero__title {
	color: #fff;
	width: 100%;
	max-width: 1300px;
	margin: 0 auto;
	padding: 0 20px;
	font-family: proxima-nova,sans-serif;
	font-weight: 700;
	font-style: normal;
	font-size: 6rem;
	line-height: 110%;
	text-align: center;
	text-transform: uppercase;
	z-index: 9;
	overflow: hidden;
	cursor: default;
	position: relative;
}
.homeHero__title {
	font-size: 9rem;
	line-height: 9rem;
	text-align: center;
    color: transparent;
    -webkit-text-stroke: 2px #fff;
}

.homeHero__title div{
    transition: 1.5s opacity ease .5s,1.5s transform ease .5s,.5s color ease,.5s -webkit-text-stroke ease,1.5s -webkit-transform ease .5s,1.5s -moz-transform ease .5s,1.5s -o-transform ease .5s;
}
.homeHero__title div:hover {
	color: #fff;
	-webkit-text-stroke: 2px #000;
}
.homeHero__clips {
	display: none;
}
.homeHero__clips {
	width: 200px;
	height: 200px;
	margin-bottom: 35px;
	object-fit: cover;
	display: block;
	-webkit-clip-path: polygon(50% 0%,99% 46%,100% 100%,70% 100%,70% 67%,30% 67%,30% 100%,0 100%,0 46%);
	clip-path: polygon(50% 0%,99% 46%,100% 100%,70% 100%,70% 67%,30% 67%,30% 100%,0 100%,0 46%);
	z-index: 10;
	mix-blend-mode: exclusion;
}
.cb-cursor {
	position: fixed;
	top: 0;
	left: 0;
	z-index: 999999999999;
	contain: layout style size;
	pointer-events: none;
	will-change: transform;
	transition: opacity .3s,color .4s;
}
.cb-cursor-text {
	position: absolute;
	top: -30px;
	left: -30px;
	width: 36px;
	height: 36px;
	display: flex;
	align-items: center;
	justify-content: center;
	opacity: 0;
	color: #1b1b1b;
	font-family: proxima-nova,sans-serif;
	font-weight: 400;
	font-style: normal;
	font-size: 1.6rem;
	line-height: 1.7rem;
	text-align: center;
	letter-spacing: -.01em;
	transition: opacity .4s,transform .3s,-webkit-transform .3s,-moz-transform .3s,-o-transform .3s;
}
.cb-cursor {
	pointer-events: none;
}
.cb-cursor.-video{
	z-index: 9;
	mix-blend-mode: exclusion;
}

.cb-cursor-video {
	transform: scale(0);
	opacity: 0;
	transition: opacity .1s,-webkit-transform .3s ease-in-out;
	transition: transform .3s ease-in-out,opacity .1s;
	transition: transform .3s ease-in-out,opacity .1s,-webkit-transform .3s ease-in-out,-moz-transform .3s ease-in-out,-o-transform .3s ease-in-out;
}
.cb-cursor.-video .cb-cursor-video{
	opacity: 1;
	transform: scale(1);
}
.cb-cursor #reel-clips {
	width: 350px;
	height: 350px;
	position: absolute;
	top: -175px;
	left: -175px;
	-o-object-fit: cover;
	object-fit: cover;
	display: block;
	-webkit-clip-path: polygon(50% 0%,99% 46%,100% 100%,70% 100%,70% 67%,30% 67%,30% 100%,0 100%,0 46%);
	clip-path: polygon(50% 0%,99% 46%,100% 100%,70% 100%,70% 67%,30% 67%,30% 100%,0 100%,0 46%);
}
</style>
<script>
    const cursor = document.querySelector(".cb-cursor");
window.onpointermove = event => {
    const { clientX, clientY } = event;
    cursor.animate({
        left: `${clientX}px`,
        top: `${clientY}px`
    }, { duration: 3000, fill: "forwards" })
}
const elements = [...document.querySelectorAll("h2 div")]
elements.map(element => {
    element.onmouseover = () => {
        cursor.classList.add("-video")
    }
    element.onmouseout = () => {
        cursor.classList.remove("-video")
    }
})
</script>
{% endblock %}

tuaz50th/templates/about1.html
{% load static %}
{% block content %}
<a href="{% url 'home' %}" style="color: transparent"> <h1>준비중!</h1> </a>

<style>
    :root {
--red: #509E2F;
--orange: #EF3340;
--yellow: #00B5E2;
--green: #509E2F;
--blue: #EF3340;
--indigo: #00B5E2;
--violet: #EF3340;
}

body {
  display: grid;
  margin: 0;
  padding: 0;
  width: 100%;
  height: 100vh;
  overflow: hidden;
  text-align: center;
  align-content: center;
  font-family: sans-serif;
  background: #aaa;
}

h1 {
  font-size: 15vw;
  color: white;
  -webkit-text-stroke: 0.015em black;
  text-shadow: 0.05em 0.05em var(--red), 0.1em 0.1em var(--orange), 0.15em 0.15em var(--yellow), 0.2em 0.2em var(--green), 0.25em 0.25em var(--blue), 0.3em 0.3em var(--indigo), 0.35em 0.35em var(--violet);
  animation: text-shadow-cascade 1s infinite steps(1);
}

@keyframes text-shadow-cascade {
  0% {
    text-shadow: 0.05em 0.05em var(--red), 0.1em 0.1em var(--orange), 0.15em 0.15em var(--yellow), 0.2em 0.2em var(--green), 0.25em 0.25em var(--blue), 0.3em 0.3em var(--indigo), 0.35em 0.35em var(--violet);
  }
  14.29% {
    text-shadow: 0.05em 0.05em var(--violet), 0.1em 0.1em var(--red), 0.15em 0.15em var(--orange), 0.2em 0.2em var(--yellow), 0.25em 0.25em var(--green), 0.3em 0.3em var(--blue), 0.35em 0.35em var(--indigo);
  }
  28.57% {
    text-shadow: 0.05em 0.05em var(--indigo), 0.1em 0.1em var(--violet), 0.15em 0.15em var(--red), 0.2em 0.2em var(--orange), 0.25em 0.25em var(--yellow), 0.3em 0.3em var(--green), 0.35em 0.35em var(--blue);
  }
  42.86% {
    text-shadow: 0.05em 0.05em var(--blue), 0.1em 0.1em var(--indigo), 0.15em 0.15em var(--violet), 0.2em 0.2em var(--red), 0.25em 0.25em var(--orange), 0.3em 0.3em var(--yellow), 0.35em 0.35em var(--green);
  }
  57.14% {
    text-shadow: 0.05em 0.05em var(--green), 0.1em 0.1em var(--blue), 0.15em 0.15em var(--indigo), 0.2em 0.2em var(--violet), 0.25em 0.25em var(--red), 0.3em 0.3em var(--orange), 0.35em 0.35em var(--yellow);
  }
  71.43% {
    text-shadow: 0.05em 0.05em var(--yellow), 0.1em 0.1em var(--green), 0.15em 0.15em var(--blue), 0.2em 0.2em var(--indigo), 0.25em 0.25em var(--violet), 0.3em 0.3em var(--red), 0.35em 0.35em var(--orange);
  }
  85.71% {
    text-shadow: 0.05em 0.05em var(--orange), 0.1em 0.1em var(--yellow), 0.15em 0.15em var(--green), 0.2em 0.2em var(--blue), 0.25em 0.25em var(--indigo), 0.3em 0.3em var(--violet), 0.35em 0.35em var(--red);
  }
  100% {
    text-shadow: 0.05em 0.05em var(--red), 0.1em 0.1em var(--orange), 0.15em 0.15em var(--yellow), 0.2em 0.2em var(--green), 0.25em 0.25em var(--blue), 0.3em 0.3em var(--indigo), 0.35em 0.35em var(--violet);
  }
}
</style>
<script></script>
{% endblock %}

tuaz50th/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- SEO Meta Tags -->
    <meta name="description" content="Tivo is a HTML landing page template built with Bootstrap to help you crate engaging presentations for SaaS apps and convert visitors into users.">
    <meta name="author" content="Inovatik">

    <!-- OG Meta Tags to improve the way the post looks when you share the page on LinkedIn, Facebook, Google+ -->
	<meta property="og:site_name" content="" /> <!-- website name -->
	<meta property="og:site" content="" /> <!-- website link -->
	<meta property="og:title" content=""/> <!-- title shown in the actual shared post -->
	<meta property="og:description" content="" /> <!-- description shown in the actual shared post -->
	<meta property="og:image" content="" /> <!-- image link, make sure it's jpg -->
	<meta property="og:url" content="" /> <!-- where do you want your post to link to -->
	<meta property="og:type" content="article" />

    <!-- Website Title -->
    <title>{%block title %}터키아제르바이잔어과 50주년{% endblock %}</title>
    
    <!-- Styles -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700&display=swap&subset=latin-ext" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/fontawesome-all.css' %}" rel="stylesheet">
    <link href="{% static 'css/swiper.css' %}" rel="stylesheet">
	<link href="{% static 'css/magnific-popup.css' %}" rel="stylesheet">
	<link href="{% static 'css/styles.css' %}" rel="stylesheet">
	{% block style %}
    {% endblock %}
	<!-- Favicon  -->
    <link rel="icon" href="https://tuaz.s3.ap-northeast-2.amazonaws.com/static/tuazicon.png">

</head>
<body data-spy="scroll" data-target=".fixed-top">
    
    <!-- Preloader -->
	<div class="spinner-wrapper" style="background-color: transparent;">
        <div class="spinner">
            <div class="bounce1" style="background-color: #00B5E2;"></div>
            <div class="bounce2" style="background-color: #EF3340;"></div>
            <div class="bounce3" style="background-color: #509E2F;"></div>
        </div>
    </div>
    <!-- end of preloader -->
    

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
        <div class="container">

            <!-- Text Logo - Use this if you don't have a graphic logo -->
            <!-- <a class="navbar-brand logo-text page-scroll" href="index.html">Tivo</a> -->

            <!-- Image Logo -->
            <a class="navbar-brand logo-image" href="{% url 'home' %}">
                <img src="https://tuaz.s3.ap-northeast-2.amazonaws.com/static/50th최종-001+(2).png" alt="alternative" style=" width: 160px; max-width: 100%; height: auto;">
            </a>
            
            
            <!-- Mobile Menu Toggle Button -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-awesome fas fa-bars"></span>
                <span class="navbar-toggler-awesome fas fa-times"></span>
            </button>
            <!-- end of mobile menu toggle button -->

            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="{% url 'intro' %}" >캐릭터소개</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="{% url 'item:all' %}">굿즈둘러보기</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="{% url 'supply:buy' %}">굿즈구매</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="{% url 'supply:find_order' %}">주문조회</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="{% url 'about' %}" >about</a>
                    </li>
                </ul>
            </div>
        </div> <!-- end of container -->
    </nav> <!-- end of navbar -->
    <!-- end of navigation -->
    <style>
        .navbar-custom {
            background-color: rgba(53, 53, 53, 0.524);
            padding: 2px;
        }
    
        .navbar-custom .navbar-brand img {
            filter: brightness(0) invert(1);
        }
    
        .navbar-custom .navbar-nav .nav-link {
            color: white;
            font-size: 18px;
        }
    
        .navbar-custom .navbar-nav .nav-link:hover,
        .navbar-custom .navbar-nav .nav-link:focus {
            color: rgba(251, 96, 96, 0.771);
        }
    </style>
    
    {% block content %}

    {%endblock%}
    
    <!-- Copyright -->
    <div class="copyright">
        <div class="container">
            <div class="row1">
                <div class="col-lg-12">
                    <div class="student-icon-div">
                        <img src="https://tuaz.s3.ap-northeast-2.amazonaws.com/static/학생회로고.png" alt="학생회 icon" class="student-icon">
                        <div class="updown"></div>
                        <p class="p-small">
                            <span class="text-content">
                                터키아제르바이잔어과 학생회  <br>
                                <a href="{% url 'my' %}">Copyright © 2023 이현제 All Rights Reserved.</a> <br>
                                관련문의 <a href="https://www.instagram.com/hufs_turkazeri/" target="_blank">@hufs_turkazeri
                                <img src="https://tuaz.s3.ap-northeast-2.amazonaws.com/static/Instagram-Icon.png" alt="Instagram Icon" class="small-icon" >   
                                </a>    
                            </span>
                        </p>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
    
    <!-- end of copyright -->
    <style>
        .copyright {
        left: 0;
        bottom: 0;
        width: 100%;
        padding: 10px 0;
        text-align: center;
        background-color: rgb(128, 128, 128);
    }
    .small-icon {
        width: 20px;
        height: 20px;
        margin-left: 5px; /* 아이콘과 텍스트 사이의 간격 조정 */
    }
    .student-icon-div {
        display: flex;
        justify-content: center;
        align-items: center;
        text-align: left;
    }
    .student-icon {
        width: 120px;
        height: 120px;
        margin-right: 1px; /* 아이콘과 텍스트 사이의 간격 조정 */
    }
    .updown {
    	border: 1px solid rgb(185, 185, 185);
        width: 0.01px;
        height: 90px;
        margin-right: 14px;
    }
    </style>
    	
    <!-- Scripts -->
    <script src="{% static 'js/jquery.min.js'%}"></script> <!-- jQuery for Bootstrap's JavaScript plugins -->
    <script src="{% static 'js/popper.min.js'%}"></script> <!-- Popper tooltip library for Bootstrap -->
    <script src="{% static 'js/bootstrap.min.js'%}"></script> <!-- Bootstrap framework -->
    <script src="{% static 'js/jquery.easing.min.js'%}"></script> <!-- jQuery Easing for smooth scrolling between anchors -->
    <script src="{% static 'js/swiper.min.js'%}"></script> <!-- Swiper for image and text sliders -->
    <script src="{% static 'js/jquery.magnific-popup.js'%}"></script> <!-- Magnific Popup for lightboxes -->
    <script src="{% static 'js/scripts.js'%}"></script> <!-- Custom scripts -->
</body>
</html> 

tuaz50th/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Header -->
<header id="header" class="header">

        <div class="container" style="padding-top: 4.5rem;">
            <div class="row">
                <div class="col-lg-7 col-xl-5.1">
                    <div class="text-container">
                        <br>
                        <h1>터키아제르바이잔어과</br>  50주년 기념샵</h1>
                        <br>
                        
                        <p class="p-large">Since 1973, 50th anniversary<br> 터키어과와 함께해주신 모든 분들께 감사드립니다.<br> Türkçe Bölümü'ne katılan herkese teşekkür ederiz.</p><h3 style="color:#ddd">프리오더기간 : 23.09.18 - 23.09.27</h3> 
                        <!-- <a class="btn-solid-lg page-scroll" href="">캐릭터소개</a>
                        <a class="btn-solid-lg page-scroll" href="{% url 'item:all' %}">굿즈둘러보기</a>
                        <a class="btn-solid-lg page-scroll" href="{% url 'supply:buy' %}">굿즈구매하기</a> -->
                        </br> </br> 
                    </div> <!-- end of text-container -->
                    <div class="cards-list">
                        <div class="card 4">
                            <a href="{% url 'item:all' %}">
                            <div class="card_image">
                              <img src="https://tuaz.s3.ap-northeast-2.amazonaws.com/static/둘러보기+진짜.png" />
                            </div>
                            <div class="card_title">
                              <p class="card_title">굿즈둘러보기</p>
                            </div>
                          </div>
                        </a>
                          <div class="card 4">
                            <a href="{% url 'supply:buy' %}">
                            <div class="card_image">
                              <img src="https://tuaz.s3.ap-northeast-2.amazonaws.com/static/%EA%B5%BF%EC%A6%88%EA%B5%AC%EB%A7%A4.png" />
                            </div>
                            <div class="card_title">
                              <p class="card_title">굿즈구매</p>
                            </div>
                          </div>
                        </a>
                          <div class="card 4">
                            <a href="{% url 'supply:find_order' %}">
                            <div class="card_image">
                              <img src="https://tuaz.s3.ap-northeast-2.amazonaws.com/item_thumbnails/img.jpg" />
                            </div>
                            <div class="card_title">
                              <p class="card_title">주문조회</p>
                            </div>
                          </div>
                        </a>
                    </div>
                </div> <!-- end of col -->
                <div class="col-lg-5 col-xl-5">
                    <div class="image-container">
                        <div class="guestbook">
                            {% for entry in guestbook_entries|slice:":6" %}
                            <div class="entry">
                                <p>{{ entry.body }}</p>
                            </div>
                            {% endfor %}
                        </div>
                        <form method="POST" action="{% url 'home' %}" class="form-guestbook">
                            {% csrf_token %}
                            <input class="form-control" type="text" placeholder="터키어과의 50주년을 축하해주세요~!" aria-label="default input example" name="body" style="color: black;">
                            <button type="submit" class="btn btn-danger">작성하기</button>
                        </form>
                    </div>
                </div> <!-- end of col -->
                
                </div>
            </div>
        </div>

</header>

    <style>
        body {
            background-image: url('{% static "images/ballon.jpg" %}');
            background-size: cover;
            background-position: center center;
            background-repeat: no-repeat;
            background-attachment: fixed;
        }
        .header {
            background-color: transparent;
            padding-bottom: 50px;
        } 
        .text-container {
        padding : 10px;
        background-color: rgba(155, 0, 0, 0.59);
        margin-bottom: 0rem !important;

        }
        
        .image-container {
        position: relative;
        padding-bottom: 60px;
        order: 1;
        }
            
        .guestbook {
        flex-wrap: wrap;
        justify-content: center;
        align-items: flex-start;
        max-height: 360px;
        overflow-y: hidden;
        padding: 10px;
        align-items: center;
        margin-top: 60px;
        }
        @media (min-width: 375px) and (max-width: 1200px) {
            .guestbook {
            margin-top: 0px;
            }
        }
        
        .entry {
        width: 100%;
        padding: 5px;
        margin-bottom: 10px;
        background-color: rgba(255, 255, 255, 0.301);
        border: 1px solid #ddd;
        border-radius: 4px;
        }

        .entry p {
        margin: 0;
        font-weight: bold;
        }

        .form-control {
        margin-bottom: 10px;
        background-color: rgba(255, 255, 255, 0.345);
        color: black;
        }

        .btn-outline-danger {
        margin-bottom: 10px;
        }
        .form-guestbook {
            position: absolute;
            left: 0;
            width: 100%;
            padding: 3px;
        }

        .form-guestbook input,
        .form-guestbook button {
            width: 100%;
            margin-bottom: 20px;
        }
        .cards-list {
        z-index: 0;
        width: 100%;
        display: flex;
        justify-content: space-around;
        flex-wrap: wrap;
        margin-top: 1rem;
        order: 2;
    }

    .card {
        margin: 30px auto;
        width: 30%;
        padding-top: 27%; /* 1:1 비율을 유지하기 위해 padding-top을 추가 */
        position: relative;
        border-radius: 40px;
        box-shadow: 2px 2px 10px 4px rgba(0,0,0,0.25), -2px -2px 10px 4px rgba(0,0,0,0.22);
        cursor: pointer;
        transition: 0.4s;
    }

    .card .card_image {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        border-radius: 40px;
        overflow: hidden;
    }

    .card .card_image img {
        width: 100%;
        height: 100%;
        object-fit: cover;
    }

    .card .card_title {
        position: absolute;
        bottom: 0;
        left: 0;
        width: 100%;
        height: 40px;
        border-radius: 0px 0px 40px 40px;
        font-family: sans-serif;
        font-weight: bold;
        text-align: center;
        font-size: auto;
        color: white;

    }

    .card:hover {
        transform: scale(0.9, 0.9);
        box-shadow: 2px 2px 10px 4px rgba(0,0,0,0.25), -2px -2px 10px 4px rgba(0,0,0,0.22);
    }

    .title-white {
        color: white;
    }

    .title-black {
        color: rgb(255, 255, 255);
    }
    </style>
</header>
    <svg class="footer-frame" data-name="Layer 2" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none" viewBox="0 0 1920 79">
        <defs>
          <linearGradient id="grad1" x1="0%" y1="0%" x2="0%" y2="100%">
            <stop offset="0%" style="stop-color:#00B5E2;stop-opacity:1" />
            <stop offset="33.33%" style="stop-color:#00B5E2;stop-opacity:1" />
            <stop offset="33.33%" style="stop-color:#EF3340;stop-opacity:1" />
            <stop offset="66.66%" style="stop-color:#EF3340;stop-opacity:1" />
            <stop offset="66.66%" style="stop-color:#509E2F;stop-opacity:1" />
            <stop offset="100%" style="stop-color:#509E2F;stop-opacity:1" />
          </linearGradient>
        </defs>
        <title>footer-frame</title>
        <path class="cls-2" d="M0,72.427C143,12.138,255.5,4.577,328.644,7.943c147.721,6.8,183.881,60.242,320.83,53.737,143-6.793,167.826-68.128,293-60.9,109.095,6.3,115.68,54.364,225.251,57.319,113.58,3.064,138.8-47.711,251.189-41.8,104.012,5.474,109.713,50.4,197.369,46.572,89.549-3.91,124.375-52.563,227.622-50.155A338.646,338.646,0,0,1,1920,23.467V79.75H0V72.427Z" transform="translate(0 -0.188)" fill="url(#grad1)" />
      </svg>
      
      
{% endblock %}