item/urls.py
from .views import *
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
app_name = 'item'

urlpatterns = [
    path('', all_items, name='all'),
    path('<int:item_id>/', item_detail, name='detail'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # 코드 추가!

supply/urls.py
from .views import *
from django.urls import path
app_name = 'supply'

urlpatterns = [
    path('', buy, name='buy'),
    path('create/', create, name='create'),
    path('all/', order_list, name='order_list'),
    path('find/', find_order, name='find_order'),
    path('cancel/<int:order_id>/', cancel_order, name='cancel_order'),
    path('delete/<int:order_id>/', delete_order, name='delete_order'),
    path('is_money/<int:order_id>/', is_money_order, name='is_money_order'),
    path('change/<int:order_id>/', change_order, name='change_order'),
]

tuaz50th/urls.py
from django.contrib import admin
from django.urls import path, include
from supply import views
from guestbook import views
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.balloon_list, name='home'),
    
    path('item/', include('item.urls')),
    path('buy/', include('supply.urls')),
    path('about/', about, name='about'),
    path('blockgame/', blockgame, name='blockgame'),
    path('audiotest/', audiotest, name='audiotest'),
    path('intro/', intro, name='intro'),
    path('leehjhjhj/', my, name='my'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/models.py
from django.db import models

class Item(models.Model):
    CATEGORY_CHOICES = (
        ('clothes', '의류'),
        ('cup', '컵'),
        ('badge', '뱃지'),
    )
    name = models.CharField(max_length=32)
    price = models.CharField(max_length=50, null=True)
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES)
    body = models.TextField(null = True)
    thumbnail = models.ImageField(upload_to='item_thumbnails/', null=True)

    def __str__(self):
        return f"{self.name}"
    

class ItemImage(models.Model):
    item = models.ForeignKey(Item, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='item_images/')

    def __str__(self):
        return f"{self.id}: {self.item.name}의 사진"

item/views.py
from django.shortcuts import render, get_object_or_404
from .models import *

def all_items(request):
    category = request.GET.get("category")
    order = ['clothes', 'cup', 'badge']

    if not category or category == 'all':
        items = Item.objects.all()
    else:
        items = Item.objects.filter(category=category)
    items = sorted(list(items), key=lambda item: order.index(item.category))

    context = {
        'items': items,
        'selected_category': category,
    }
    return render(request, 'all_items.html', context)

def item_detail(request, item_id):
    item_detail = get_object_or_404(Item, pk=item_id)
    item_photos = ItemImage.objects.filter(item=item_id)
    related_items = Item.objects.filter(category=item_detail.category).exclude(pk=item_id)
    context = {
        'item_detail': item_detail,
        'item_photos': item_photos,
        'related_items': related_items,
    }
    return render(request, 'item_detail.html', context)

item/templates/all_items.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block content %}
<div style="margin-top: 6rem;">
  <div class="container">
    <div class="row" style="padding-top: 10px; background-color: rgba(86, 86, 86, 0.452); height: auto;">
      <div class="col-lg-6" style="text-align: left;">
        <h1 style="text-align: left; color: #fff; margin-bottom: 30px;">굿즈 둘러보기</h1>
      </div>
      <div class="col-lg-6" style="margin-top: 10px;">
        <div class="d-flex align-items-center justify-content-start">
          {% url 'item:all' as item_all_url %}
          <select class="custom-select custom-select mb-3 float-right" style="border: 2px solid rgba(255, 255, 255, 0.664); background-color: rgba(255, 255, 255, 0.846);" onchange="location.href = '{{ item_all_url }}?category=' + this.value;">
            <option value="all">전체</option>
            <option {% if selected_category == 'clothes' %}selected{% endif %} value="clothes">의류</option>
            <option {% if selected_category == 'cup' %}selected{% endif %} value="cup">컵</option>
            <option {% if selected_category == 'badge' %}selected{% endif %} value="badge">뱃지</option>
          </select>
        </div>
      </div>
    </div>
    <div class="row" style="margin-bottom: 0;">
      {% for item in items %}
      <div class="col-xl-4 col-md-6 mb-4">
        <a href="{% url 'item:detail' item.id %}" style="text-decoration: none;">
          <div class="card h-100 card-hover">
            <div class="card-img-container">
              <div class="image-wrapper">
                <img src="{{ item.thumbnail.url }}" class="card-img-top" alt="{{ item.name }}">
              </div>
              <div class="overlay"></div>
            </div>
            <div class="card-body">
              <h5 class="card-title">{{ item.name }}</h5>
              <h5 class="card-title">{{ item.price|intcomma }}원</h5>
            </div>
          </div>
        </a>
      </div>
      {% empty %}
      <div class="col-xl-4 col-md-6 mb-4"></div>
      {% endfor %}
    </div>
  </div>
</div>
<style>
  body {
    background-image: url('{% static "images/ballon.jpg" %}');
    background-size: cover;
    background-position: center center;
    background-repeat: no-repeat;
    background-attachment: fixed;
  }
  
  .card {
    height: 100%;
  }

  .card-hover:hover {
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
  }

  .card-img-container {
    position: relative;
  }

  .card-img-container .overlay {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(144, 144, 144, 0.199);
    opacity: 0;
    z-index: 1;
    transition: opacity 0.3s ease;
  }

  .card-hover:hover .overlay {
    opacity: 1;
  }

  /* Adjusted row styling */
  .row {
    background-color: rgba(86, 86, 86, 0.452);
    margin-bottom: 0; /* Remove default margin-bottom */
  }

  /* Add a custom class to the footer to differentiate styling */
  .custom-footer {
    background-color: #f8f9fa; /* Specify desired footer background color */
    padding: 20px; /* Add appropriate padding to the footer */
  }
  
  @media (min-width: 300px) {
    .col-xl-4 {
      flex: 0 0 50%;
      max-width: 50%;
    }
  }
  @media (min-width: 992px) {
    .col-xl-4 {
      flex: 0 0 33.333333%;
      max-width: 33.333333%;
    }
  }

  @media (min-width: 1200px) {
    .col-xl-4 {
      flex: 0 0 25%;
      max-width: 25%;
    }
  }
</style>
<svg class="footer-frame" data-name="Layer 2" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none" viewBox="0 0 1920 79">
  <defs>
    <linearGradient id="grad1" x1="0%" y1="0%" x2="0%" y2="100%">
      <stop offset="0%" style="stop-color:#00B5E2;stop-opacity:1" />
      <stop offset="33.33%" style="stop-color:#00B5E2;stop-opacity:1" />
      <stop offset="33.33%" style="stop-color:#EF3340;stop-opacity:1" />
      <stop offset="66.66%" style="stop-color:#EF3340;stop-opacity:1" />
      <stop offset="66.66%" style="stop-color:#509E2F;stop-opacity:1" />
      <stop offset="100%" style="stop-color:#509E2F;stop-opacity:1" />
    </linearGradient>
  </defs>
  <title>footer-frame</title>
  <path class="cls-2" d="M0,72.427C143,12.138,255.5,4.577,328.644,7.943c147.721,6.8,183.881,60.242,320.83,53.737,143-6.793,167.826-68.128,293-60.9,109.095,6.3,115.68,54.364,225.251,57.319,113.58,3.064,138.8-47.711,251.189-41.8,104.012,5.474,109.713,50.4,197.369,46.572,89.549-3.91,124.375-52.563,227.622-50.155A338.646,338.646,0,0,1,1920,23.467V79.75H0V72.427Z" transform="translate(0 -0.188)" fill="url(#grad1)" />
</svg>
{% endblock %}

item/templates/item_detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block content %}
    <!-- Product section-->
    <section class="py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="row gx-4 gx-lg-5 align-items-center">
                <div class="col-md-6">
                    <div class="big-image-container">
                        <img class="card-img-top mb-5 mb-md-0" src="{{ item_detail.thumbnail.url }}" alt="{{ item_detail.name }}" style="object-fit: cover"/>
                    </div>
                    <div class="info-container" style="padding: 40px;">
                        <div class="info-in-container">
                            <h1 class="display-5 fw-bolder">{{ item_detail.name }}</h1>
                            <div class="fs-5 mb-5">
                                <span class="text-decoration-line-through">{{ item_detail.price|intcomma }}원</span>
                            </div>
                        </div>
                        <p class="lead" style="font-size: 18px;">{{ item_detail.body|linebreaks }}</p>
                        <div class="d-flex align-items-center">
                        </div>
                    </div>
                </div>
                
                <div class="col-md-6" style="padding-top: 30px; text-align: center;">
                    <h2 class="fw-bolder mb-4">Detail</h2>
                    <div style="display: inline-block; text-align: center;">
                        {% for item_photo in item_photos %}
                            <div class="item-photo" style="width: 80%; display: inline-block;">
                                <img src="{{ item_photo.image.url }}" alt="Item Photo" class="img-fluid img-cover">
                                <br>
                            </div>
                        {% endfor %}
                    </div>
                    <a href="{% url 'supply:buy' %}">
                    <button type="button" name="go_buy" class="form-control-submit-button" id="submit-btn" style="margin: 0px">구매하기</button>
                    </a>
                </div>
                
        </div>
    </section>
  
    <!-- Related items section -->
    <section class="py-5 bg-light">
        <div class="container px-4 px-lg-5 mt-5">
            <h2 class="fw-bolder mb-4">Related products</h2>
            <div class="row" style="margin-bottom: 0;">
                {% for related_item in related_items %}
                <div class="col-xl-4 col-md-6 mb-4">
                    <a href="{% url 'item:detail' related_item.id %}" style="text-decoration: none;">
                        <div class="card h-100 card-hover">
                            <div class="card-img-container">
                                <div class="image-wrapper">
                                    <img src="{{ related_item.thumbnail.url }}" class="card-img-top" alt="{{ related_item.name }}">
                                </div>
                                <div class="overlay"></div>
                            </div>
                            <div class="card-body">
                                <h5 class="card-title">{{ related_item.name }}</h5>
                                <h5 class="card-title">{{ related_item.price }}원</h5>
                            </div>
                        </div>
                    </a>
                </div>
                {% empty %}
                <div class="col-xl-4 col-md-6 mb-4"></div>
                {% endfor %}
            </div>
        </div>
    </section>
  
    <style>
        .big-image-container {
            width: 50%;
            float: left;
            position: relative;
            overflow: hidden;
            padding-right: 15px;
        }

        .image-container {
            width: 100%;
            position: relative;
            overflow: hidden;
        }

        .card-img-top {
            width: 100%;
            height: 100%;
            object-fit: cover;
        }

        .info-container {
            width: 50%;
            float: right;

            padding-left: 15px;
        }

        .item-photo {
            margin-bottom: 50px;
            position: relative;
        }

        .img-cover {
            object-fit: cover;
            width: 100%;
            height: 100%;
        }

        .card {
            height: 100%;
        }

        .card-hover:hover {
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
        }

        .card-img-container {
            position: relative;
        }

        .card-img-container .overlay {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(144, 144, 144, 0.199);
            opacity: 0;
            z-index: 1;
            transition: opacity 0.3s ease;
        }

        .card-hover:hover .overlay {
            opacity: 1;
        }

        @media (max-width: 768px) {
            .big-image-container,
            .info-container {
                width: 100%;
                float: none;
                margin-right: 0;
                padding: 0;
            }
            }
            @media (min-width: 300px) {
            .col-xl-4 {
            flex: 0 0 50%;
            max-width: 50%;
            }
        }
        @media (min-width: 992px) {
            .col-xl-4 {
            flex: 0 0 33.333333%;
            max-width: 33.333333%;
            }
        }

        @media (min-width: 1200px) {
            .col-xl-4 {
            flex: 0 0 25%;
            max-width: 25%;
            }
        }
    </style>
{% endblock %}