item/urls.py
from .views import *
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
app_name = 'item'

urlpatterns = [
    path('', all_items, name='all'),
    path('<int:item_id>/', item_detail, name='detail'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # 코드 추가!

supply/urls.py
from .views import *
from django.urls import path
app_name = 'supply'

urlpatterns = [
    path('', buy, name='buy'),
    path('create/', create, name='create'),
    path('all/', order_list, name='order_list'),
    path('find/', find_order, name='find_order'),
    path('cancel/<int:order_id>/', cancel_order, name='cancel_order'),
    path('delete/<int:order_id>/', delete_order, name='delete_order'),
    path('is_money/<int:order_id>/', is_money_order, name='is_money_order'),
    path('change/<int:order_id>/', change_order, name='change_order'),
]

tuaz50th/urls.py
from django.contrib import admin
from django.urls import path, include
from supply import views
from guestbook import views
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.balloon_list, name='home'),
    
    path('item/', include('item.urls')),
    path('buy/', include('supply.urls')),
    path('about/', about, name='about'),
    path('blockgame/', blockgame, name='blockgame'),
    path('audiotest/', audiotest, name='audiotest'),
    path('intro/', intro, name='intro'),
    path('leehjhjhj/', my, name='my'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

supply/models.py
from django.db import models
from item.models import *

class Order(models.Model):
    STATUS_CHOICES = (
        ('waiting', '입금 대기'),
        ('completed', '입금 완료'),
        ('cancel_wait', '취소 대기'),
        ('canceled', '취소 완료'),
    )
    number_name = models.CharField(max_length=10, default="임시")
    name = models.CharField(max_length=10)
    phone = models.CharField(max_length=11)
    email = models.EmailField(max_length=50)
    grade = models.IntegerField()
    all_price = models.IntegerField()
    status = models.CharField(max_length=20, choices=STATUS_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    password = models.CharField(max_length=4, default="0000")
    
    def __str__(self):
        return f"주문번호:{self.id} | {self.number_name} | {self.get_status_display()}"
    
class OrderItems(models.Model):
    order = models.ForeignKey(Order,related_name='order', on_delete=models.CASCADE)
    item = models.ForeignKey(Item, related_name='item', on_delete=models.CASCADE)
    quantity = models.IntegerField()
    size = models.CharField(max_length=10, null=True)

    def __str__(self):
        return f"{self.order.number_name} | 주문번호:{self.order.id} | {self.item.name} | {self.quantity}"

class Cancel(models.Model):
    order = models.ForeignKey(Order,related_name='cancel_order', on_delete=models.CASCADE)
    bank = models.CharField(max_length=10)
    account = models.CharField(max_length=32)
    account_holder = models.CharField(max_length=10)

    def __str__(self):
        return f"{self.order.number_name} | 주문번호: {self.order.id} | {self.order.get_status_display()}"

supply/forms.py
from django import forms
from .models import *

supply/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from item.models import *
from .models import *


def buy(request):
    all_item = Item.objects.all().exclude(price=0)
    context = {
        'all_item': all_item,
    }
    #return render(request, 'buy.html', context)
    return render(request, 'notyet.html')

def create(request):
    if request.method == 'POST':  
        new_order = Order()
        new_order.name = request.POST['name']   
        new_order.phone = request.POST['phone'] 
        email_id = request.POST['email_id']   
        email_server = request.POST['email_server']
        new_order.email = email_id + '@' + email_server
        new_order.grade = request.POST['grade']
        new_order.all_price = request.POST['total-price-input']
        new_order.password = request.POST['password']
        new_order.status = 'waiting'

        new_order.number_name = request.POST['grade'] + " " + request.POST['name']
        new_order.save()


        product_names = request.POST.getlist('category[]')
        sizes = request.POST.getlist('size-category[]')
        quantities = request.POST.getlist('quantity[]')
        
        for i in range(len(product_names)):
            product_name = product_names[i]
            size = sizes[i]
            quantity = quantities[i]
            
            new_order_item = OrderItems()
            new_order_item.order = new_order
            new_order_item.item = Item.objects.get(name=product_name)
            if not new_order_item.item.category == 'clothes':
                new_order_item.size = '없음'
            else:
                new_order_item.size = size
            new_order_item.quantity = quantity
            new_order_item.save()

        context = {
            'order': new_order
        }
        return render(request, 'order_one.html', context)
    return redirect('supply:order_list')

def order_list(request):
    orders = Order.objects.all()
    context = {
        'orders': orders
        }
    return render(request, 'order_list.html', context)


def find_order(request):
    if request.method == 'GET':
        return render(request, 'find_order_input.html')
        #return render(request, 'notyet.html')
    elif request.method == 'POST':
        phone = request.POST['phone']
        password = request.POST['password']
        orders = Order.objects.filter(phone=phone, password=password)
        if orders:
            context = {
                'orders': orders
                }
            return render(request, 'find_order.html', context)
        else:
            return render(request, 'fail.html')


def cancel_order(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    if request.method == 'GET':
        context = {
            'order': order
        }
        return render(request, 'order_cancel.html', context)
    elif request.method == 'POST':

        new_cancel = Cancel()
        new_cancel.order = order
        new_cancel.account = request.POST['account']
        new_cancel.bank = request.POST['bank']
        new_cancel.account_holder = request.POST['account_holder']
        new_cancel.save()

        order.status = 'cancel_wait'
        order.save()
        return render(request, 'order_cancel_complete.html') 

def delete_order(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    if request.method == 'POST':
        order.delete()
    return render(request, 'order_cancel_complete.html')  


def is_money_order(request, order_id):
    context = {'order_id': order_id}
    if request.method == 'GET':
        return render(request, 'order_cancel_isMoney.html', context)
    elif request.method == 'POST':
        if request.POST['is_money'] == 'yes':
            return redirect('supply:cancel_order', order_id=order_id)
        else:
            order = get_object_or_404(Order, id=order_id)
            order.status = 'canceled'
            order.save()
    return render(request, 'order_cancel_complete.html') 

def change_order(request, order_id):
    order = get_object_or_404(Order, id=order_id)

    if request.method == 'GET':
        context ={
            'order': order
        }
        return render(request, 'order_change.html', context)
    
    elif request.method == 'POST':
        new_grade = request.POST['new_grade']
        new_name = request.POST['new_name']

        order.number_name = new_grade + ' ' + new_name
        order.grade = new_grade
        order.name = new_name
        
        order.phone = request.POST['new_phone']
        order.email = request.POST['new_email']
        order.save()
    
        return render(request, 'order_cancel_complete.html')

supply/templates/fail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    
    <!-- Header -->
    <!-- Header -->
<header id="header" class="ex-2-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="form-container" style="max-width: 80rem;">
                    <div class="order-info" style="color: black;">
                        <h1 style="color: black;">주문 결과가 없습니다.</h1><br>해당 주문 건에 대한 핸드폰 번호와 비밀번호가 일치해야합니다.
                        <br>비밀번호가 기억나지 않는다면 문의 바랍니다.<br>문의사항 : <ins><b>010-5041-9890</ins></b>(터키아제르바이잔어과 제 36대 학생회장 송준엽)<br>Teşekkur ederim!</h2>
                    </div> <!-- end of order-info -->
                </div> <!-- end of form container -->
            </div> <!-- end of col -->
        </div> <!-- end of row -->
    </div> <!-- end of container -->
</header> <!-- end of ex-header -->
<!-- end of header -->

<style>
    .ex-2-header {
            background-color: transparent;
        }
        header {
            background-image: url('{% static "images/ballon.jpg" %}');
            background-size: cover;
            background-position: center center;
            background-repeat: no-repeat;
            background-attachment: fixed;
        }
    .p {
        color: black;
    }
</style>
{% endblock %}

supply/templates/find_order.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load humanize %}
    <!-- Header -->
    <!-- Header -->
<header id="header" class="ex-2-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="form-container" style="max-width: 80rem;">
                    <main>
                        <div class="detail_box">
                            {% for order in orders %}
                            <hr style="border: 0; height: 3px; background: black;">
                            <div class="order_cont">
                                <br>
                                <div class="store_name">주문번호: {{ order.id }}</div>
                                <br>
                                <div class="order_info">
                                    <div style="padding-bottom: 5px;">
                                        주문일시 :
                                        {{ order.created_at}}
                                    </div>
                                    <div style="padding-bottom: 5px; font-weight: bolder;">입금상태:
                                        {% if order.status == 'waiting' %}
                                        입금 대기
                                        {% elif order.status == 'completed' %}
                                        입금 완료
                                        {% elif order.status == 'cancel_wait' %}
                                        취소 대기
                                        {% else %}
                                        취소 완료
                                        {% endif %}
                                    </div>
                                    <div style="padding-bottom: 5px;">학번이름: {{ order.number_name }}</div>
                                    <div style="padding-bottom: 5px;">전화번호: {{ order.phone }}</div>
                                    <div style="padding-bottom: 5px;">이메일: {{ order.email }}</div>
                                
                                </div>
                            </div>
                            <hr>
                            <ul class="order_menu">
                                {% for item in order.order.all %}
                                    <div class="menu_item">
                                        <div class="thumbnail">
                                            <img src="{{ item.item.thumbnail.url }}" alt="{{ item.item.name }} thumbnail">
                                        </div>
                                        <div class="menu_info" style="font-size: 1.0rem;">
                                            <span>{{ item.item.name }}</span><br/>
                                            <span>{{ item.quantity }}개</span><br/>
                                            <span> 
                                                {% if item.size == 's' %}
                                                사이즈: S
                                                {% elif item.size == 'm' %}
                                                사이즈: M
                                                {% elif item.size == 'l' %}
                                                사이즈: L
                                                {% elif item.size == 'xl' %}
                                                사이즈: XL
                                                {% elif item.size == '2xl' %}
                                                사이즈: 2XL
                                                {% endif %}
                                            </span>
                                        </div>
                                        <ul>
                                            <span class="menu_price_sum">{{ item.item.price|intcomma }}원</span>
                                        </ul>
                                    </div>
                                    <hr>
                                {% endfor %}
                            </ul>
                    
                            <div class="price">
                                <div>
                                    <span>총 주문금액</span>
                                    <span>{{ order.all_price|intcomma }}원</span>
                                </div>
                                <hr>
                            </div>
                            <!-- {% if order.status == 'waiting' %}
                            <div class="button-container">
                                <form method="get" action="{% url 'supply:is_money_order' order.id %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger">주문 취소</button>
                                </form>
                                <form method="get" action="{% url 'supply:change_order' order.id %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-success" style="margin-left: 10px;">주문 변경</button>
                                </form>
                            </div>
                            {% elif order.status == 'completed' %}
                            <div class="button-container">
                                <form method="get" action="{% url 'supply:cancel_order' order.id %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger">주문 취소</button>
                                </form>
                                <form method="get" action="{% url 'supply:change_order' order.id %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-success" style="margin-left: 10px;">주문 변경</button>
                                </form>
                            </div>
                            {% elif order.status == 'cancel_wait' %}
                            취소 절차가 진행 중입니다.
                            {% else %}
                            취소된 주문입니다.<br/>
                            <form method="post" action="{% url 'supply:delete_order' order.id %}" style="padding-top: 10px;">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-secondary">내역 삭제</button>
                            </form>
                            {% endif %}
                        {% endfor %}    -->
                        </div>
                        
                    </main>
                </div> <!-- end of form container -->
            </div> <!-- end of col -->
        </div> <!-- end of row -->
    </div> <!-- end of container -->
    <svg class="footer-frame" data-name="Layer 2" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none" viewBox="0 0 1920 79">
        <defs>
          <linearGradient id="grad1" x1="0%" y1="0%" x2="0%" y2="100%">
            <stop offset="0%" style="stop-color:#00B5E2;stop-opacity:1" />
            <stop offset="33.33%" style="stop-color:#00B5E2;stop-opacity:1" />
            <stop offset="33.33%" style="stop-color:#EF3340;stop-opacity:1" />
            <stop offset="66.66%" style="stop-color:#EF3340;stop-opacity:1" />
            <stop offset="66.66%" style="stop-color:#509E2F;stop-opacity:1" />
            <stop offset="100%" style="stop-color:#509E2F;stop-opacity:1" />
          </linearGradient>
        </defs>
        <title>footer-frame</title>
        <path class="cls-2" d="M0,72.427C143,12.138,255.5,4.577,328.644,7.943c147.721,6.8,183.881,60.242,320.83,53.737,143-6.793,167.826-68.128,293-60.9,109.095,6.3,115.68,54.364,225.251,57.319,113.58,3.064,138.8-47.711,251.189-41.8,104.012,5.474,109.713,50.4,197.369,46.572,89.549-3.91,124.375-52.563,227.622-50.155A338.646,338.646,0,0,1,1920,23.467V79.75H0V72.427Z" transform="translate(0 -0.188)" fill="url(#grad1)" />
      </svg>
</header>
<!-- end of ex-header -->
<!-- end of header -->

<style>
    .order_menu {
        list-style: none;
        padding: 0;
    }

    .menu_item {
        display: flex;
        align-items: center;
        margin-bottom: 10px;
    }

    .thumbnail {
        margin-right: 10px;
    }

    .menu_info {
        flex: 1;
    }

    .menu_price_sum {
        margin-top: auto;
    }

    .ex-2-header {
            background-color: transparent;
        }
        header {
            background-image: url('{% static "images/ballon.jpg" %}');
            background-size: cover;
            background-position: center center;
            background-repeat: no-repeat;
            background-attachment: fixed;
        }
        main {
	width: 800px;
	margin : 0 auto 50px ;
} 
 
.detail_box {
	width: 95%;
	margin-left: auto;
}
 
section.title {
    width: 100%;
}
 
section.title h1 {
    text-align: center;
    margin : 30px 0 50px 0 ;
}
 
main .order_cont {
	margin-bottom: 30px;
}
 
main div {
    font-size: 1.2rem;
}
 
main .order_cont .store_name {
	font-size: 2rem;
	font-weight: bold;
	
}
 
main .order_cont .order_info {
	margin-top: 10px;
	
}
 
main .order_menu  {
    margin-bottom: 30px;
}
 
main .order_menu li {
    position: relative;
}
 
main .order_menu li div,
main .price div,
main .total div {
    display: flex;
    justify-content: space-between;
 
}
 
main .order_menu li .menu_price,
main .price div span:last-child,
main .total div span:last-child {
    position: relative;
    right: 0;
}
 
main .order_menu li ul li {
    
    list-style: disc;
    margin-left: 20px;
    color: #a5a5a5;
}
 
main .order_menu li ul li.menu_price_sum {
	list-style: none;
	margin: 0;
	color: black;
	font-weight: bold;
	
}
 
main .price {
    margin-bottom: 30px;
}
 
 
main .price div {
    font-weight: bold;
    font-size: 1.4rem;
}
 
main .total{
    margin-bottom: 30px;
}
 
main .total div {
	font-size: 2rem;
	font-weight: bold;
}
.thumbnail img {
        width: 100px; /* Adjust the width as needed */
        height: auto; /* Maintain the aspect ratio */
    }
    .button-container {
        display: flex;
        justify-content: left;
        margin-top: 20px;
    }
 
@media (max-width:1024px) {
	main {
		width: 95%;
	}
	.detail_box {
		margin: 0 auto;
		
	}
}
@media  (max-width:767px) {
	
}
</style>
{% endblock %}

supply/templates/find_order_input.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    
    <!-- Header -->
    <!-- Header -->
<header id="header" class="ex-2-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="form-container" style="max-width: 80rem;">
                    <h2 style="color: black;">주문 조회</h2>
                    <div class="order-info" style="color: black;">
                        <form method="POST" action="{% url 'supply:find_order' %}" id="find_order">
                            {% csrf_token %}
                            <div class="form-group">
                                1. 주문할 때 작성하신 핸드폰 번호를 작성해주세요 ('-' 없이 8자리)
                                <input class="form-control" type="text" placeholder="010xxxxxxxx" aria-label=".form-control-lg example" name="phone" required maxlength="11">
                            </div>
                            <div class="form-group">
                                2. 주문할 때 설정하신 패스워드를 입력해주세요
                                <input class="form-control" type="text" placeholder="" aria-label=".form-control-lg example" name="password" style="width:250px;" required maxlength="4">
                                <div class="help-block with-errors"></div>
                            </div>
                            <br>
                            <button type="submit" name="draft" class="form-control-submit-button" id="submit-btn">주문조회</button>
                        </form>
                    </div> <!-- end of order-info -->
                </div> <!-- end of form container -->
            </div> <!-- end of col -->
        </div> <!-- end of row -->
    </div> <!-- end of container -->
    
</header> <!-- end of ex-header -->
<!-- end of header -->

<style>
    .ex-2-header {
            background-color: transparent;
        }
        header {
            background-image: url('{% static "images/ballon.jpg" %}');
            background-size: cover;
            background-position: center center;
            background-repeat: no-repeat;
            background-attachment: fixed;

        }
        .form-control-submit-button {
            display: inline-block;
            width: 50%;
            height: 3.125rem;
            border: 1px solid #ff0000;
            border-radius: 1.5rem;
            background-color: #ff0000;
            color: #fff;
            font: 700 0.875rem/0 "Open Sans", sans-serif;
            cursor: pointer;
            transition: all 0.2s;
            margin-left: 25%;
        }
        .form-control-submit-button:hover {
            background-color: transparent;
            color: #ff0000;
        }
</style>


{% endblock %}

supply/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Header -->
<header id="header" class="header">
    <div class="header-content">
        <div class="container" >
            <div class="row">
                <div class="col-lg-7 col-xl-5.1">
                    <div class="text-container">
                        <br>
                        <h1>터키아제르바이잔어과</br>  50주년 기념샵</h1>
                        <p class="p-large">Since 1973, 50th anniversary<br> 터키어과와 함께해주신 모든 분들께 감사드립니다. </p>
                        <a class="btn-solid-lg page-scroll" href="">캐릭터소개</a>
                        <a class="btn-solid-lg page-scroll" href="{% url 'item:all' %}">굿즈둘러보기</a>
                            <a class="btn-solid-lg page-scroll" href="">굿즈구매하기</a>
                        </br> </br> 
                    </div> <!-- end of text-container -->
                </div> <!-- end of col -->
                <div class="col-lg-5 col-xl-5">
                    <div class="image-container">
                        <div class="guestbook">
                            {% for entry in guestbook_entries %}
                            <div class="entry">
                                <p>{{ entry.body }}</p>
                            </div>
                            {% endfor %}
                        </div>
                        <form method="POST" action="{% url 'home' %}" class="form-guestbook">
                            {% csrf_token %}
                            <input class="form-control" type="text" placeholder="터키어과의 50주년을 축하해주세요~!" aria-label="default input example" name="body" style="color: black;">
                            <button type="submit" class="btn btn-danger">작성하기</button>
                        </form>
                    </div>
                </div> <!-- end of col -->
            </div> <!-- end of row -->
        </div> <!-- end of container -->
    </div> <!-- end of header-content -->
    <style>
        body {
            background-image: url('{% static "images/ballon.jpg" %}');
            background-size: cover;
            background-position: center center;
            background-repeat: no-repeat;
            background-attachment: fixed;
        }
        .header {
            background-color: transparent;
        } 
        .text-container {
        padding: 20px;
        background-color: rgba(155, 0, 0, 0.59);
        }
        
        .image-container {
        position: relative;
        padding-bottom: 60px;
        }
            
        .guestbook {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        align-items: flex-start;
        max-height: 360px;
        overflow-y: hidden;
        padding: 10px;
        align-items: center;
 
        }

        .entry {
        width: 100%;
        padding: 10px;
        margin-bottom: 10px;
        background-color: rgba(255, 255, 255, 0.345);
        border: 1px solid #ddd;
        border-radius: 4px;
        }

        .entry p {
        margin: 0;
        }

        .form-control {
        margin-bottom: 10px;
        background-color: rgba(255, 255, 255, 0.345);
        color: black;
        }

        .btn-outline-danger {
        margin-bottom: 10px;
        }
        .form-guestbook {
            position: absolute;
            bottom: 5;
            left: 0;
            width: 100%;
            padding: 10px;
        }

        .form-guestbook input,
        .form-guestbook button {
            width: 100%;
            margin-bottom: 20px;
        }
    </style>
</header>
    
    <svg class="footer-frame" data-name="Layer 2" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none" viewBox="0 0 1920 79">
        <defs>
          <linearGradient id="grad1" x1="0%" y1="0%" x2="0%" y2="100%">
            <stop offset="0%" style="stop-color:#00B5E2;stop-opacity:1" />
            <stop offset="33.33%" style="stop-color:#00B5E2;stop-opacity:1" />
            <stop offset="33.33%" style="stop-color:#EF3340;stop-opacity:1" />
            <stop offset="66.66%" style="stop-color:#EF3340;stop-opacity:1" />
            <stop offset="66.66%" style="stop-color:#509E2F;stop-opacity:1" />
            <stop offset="100%" style="stop-color:#509E2F;stop-opacity:1" />
          </linearGradient>
        </defs>
        <title>footer-frame</title>
        <path class="cls-2" d="M0,72.427C143,12.138,255.5,4.577,328.644,7.943c147.721,6.8,183.881,60.242,320.83,53.737,143-6.793,167.826-68.128,293-60.9,109.095,6.3,115.68,54.364,225.251,57.319,113.58,3.064,138.8-47.711,251.189-41.8,104.012,5.474,109.713,50.4,197.369,46.572,89.549-3.91,124.375-52.563,227.622-50.155A338.646,338.646,0,0,1,1920,23.467V79.75H0V72.427Z" transform="translate(0 -0.188)" fill="url(#grad1)" />
      </svg>
      
      
{% endblock %}

supply/templates/order_cancel_isMoney.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    
    <!-- Header -->
    <!-- Header -->
    <header id="header" class="ex-2-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="form-container" style="max-width: 80rem;">
                        <div class="order-info" style="color: black;">
                            <h1 style="color: black;">주문 취소</h1>
                            <div id="cancel-form-container">
                                <div>
                                    현재 입금 상태는 '입금 대기'이지만, 계좌 이체를 진행 했을 경우 '예' 버튼을 눌러주세요.<br>
                                    계좌 이체를 했음에도 불구하고 '아니오'를 누를 시, 즉시 '취소 완료'가 되어서 환불 진행에 차질이 생깁니다.
                                </div>
                                <div class="button-container">
                                    <form method="POST" action="{% url 'supply:is_money_order' order_id %}" id="yesno-form" style="display: flex; justify-content: center;">
                                        {% csrf_token %}
                                        <button type="submit" name="is_money" value="yes" class="form-control-submit-button-yes" id="submit-btn-yes" style="width: 150px;">예</button>
                                        <button type="submit" name="is_money" value="no" class="form-control-submit-button-no" id="submit-btn-no" style="width: 150px; margin-left: 10px;">아니오</button>
                                    </form>
                                </div>
                            </div>
                        </div> <!-- end of order-info -->
                    </div> <!-- end of form container -->
                </div> <!-- end of col -->
            </div> <!-- end of row -->
        </div> <!-- end of container -->
    </header>
    
    
<!-- end of header -->
<style>
    .ex-2-header {
            background-color: transparent;
        }
        header {
            background-image: url('{% static "images/ballon.jpg" %}');
            background-size: cover;
            background-position: center center;
            background-repeat: no-repeat;
            background-attachment: fixed;
        }
    .p {
        color: black;
    }
    .form-control-submit-button-yes {
            display: inline-block;
        
            height: 3.125rem;
            border: 1px solid #00B5E2;
            border-radius: 1.5rem;
            background-color: #00B5E2;
            color: #fff;
            font: 700 0.875rem/0 "Open Sans", sans-serif;
            cursor: pointer;
            transition: all 0.2s;
            
        }
        .form-control-submit-button-yes:hover {
            background-color: transparent;
            color: #00B5E2;
        }
        .form-control-submit-button-no {
            display: inline-block;
            height: 3.125rem;
            border: 1px solid #509E2F;
            border-radius: 1.5rem;
            background-color: #509E2F;
            color: #fff;
            font: 700 0.875rem/0 "Open Sans", sans-serif;
            cursor: pointer;
            transition: all 0.2s;
            
        }
        .form-control-submit-button-no:hover {
            background-color: transparent;
            color: #a1d78a;
        }
        .button-container {
        display: flex;
        justify-content: center;
        margin-top: 20px;
    }
    @media (min-width: 768px) {
        .form-control-submit-button-yes,
        .form-control-submit-button-no {
            width: 100px;
        }    
    }
    @media (min-width: 300px) {
    .form-control-submit-button-yes,
    .form-control-submit-button-no{
        width: 100px;
    }
  }
</style>
{% endblock %}